---
- name: Deploy Flask App with Gunicorn and Nginx
  hosts: web
  become: yes

  tasks:
    - name: Update apt
      apt:
        update_cache: yes

    - name: Install dependencies
      apt:
        name:
          - python3-pip
          - python3-venv
          - nginx
        state: present

    - name: Create flask app directory
      file:
        path: /home/ubuntu/flask-app
        state: directory

    - name: Copy app.py
      copy:
        src: ./app/app.py
        dest: /home/ubuntu/flask-app/app.py

    - name: Copy requirements.txt
      copy:
        src: ./app/requirements.txt
        dest: /home/ubuntu/flask-app/requirements.txt

    - name: Create virtual environment
      command: python3 -m venv venv
      args:
        chdir: /home/ubuntu/flask-app

    - name: Install dependencies inside venv
      pip:
        requirements: /home/ubuntu/flask-app/requirements.txt
        virtualenv: /home/ubuntu/flask-app/venv

    - name: Create Gunicorn systemd service
      copy:
        dest: /etc/systemd/system/gunicorn.service
        content: |
          [Unit]
          Description=Gunicorn daemon
          After=network.target

          [Service]
          User=ubuntu
          Group=www-data
          WorkingDirectory=/home/ubuntu/flask-app
          Environment="PATH=/home/ubuntu/flask-app/venv/bin"
          ExecStart=/home/ubuntu/flask-app/venv/bin/gunicorn -w 3 -b 127.0.0.1:8000 app:app

          [Install]
          WantedBy=multi-user.target

    - name: Start and enable Gunicorn
      systemd:
        name: gunicorn
        enabled: yes
        state: started

    - name: Setup Nginx config
      copy:
        dest: /etc/nginx/sites-available/flask
        content: |
          server {
              listen 80;
              server_name _;

              location / {
                  proxy_pass http://127.0.0.1:8000;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }
          }

    - name: Enable Nginx site
      file:
        src: /etc/nginx/sites-available/flask
        dest: /etc/nginx/sites-enabled/flask
        state: link
        force: yes

    - name: Remove default Nginx site
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Restart Nginx
      systemd:
        name: nginx
        state: restarted
